### ISSUE TITLE
[BUG] Config remote daemon does not work

### ISSUE THREAD

**Issue by pyDraco9** [silicoin-network/silicoin-blockchain#190]
Config GUI wallet on windows like this:
```
ui:
  daemon_host: 192.168.2.2
  daemon_port: 56402
  daemon_ssl:
    private_crt: config/ssl/ui/private_daemon.crt
    private_key: config/ssl/ui/private_daemon.key
```
But it not work.
Server use default config:
`daemon_port: 56402`
This worked on chia: https://github.com/Chia-Network/chia-blockchain/wiki/Connecting-the-UI-to-a-remote-daemon
